import streamlit  as st
st.title("MY FIRST STREAMLIT APP")
st.write("im happy now")
st.header("this is a header")
st.text("this is a text")
st.text_input("enter your name")
st.text_input("enter your email")
a = st.number_input("enter a number")
st.button("submit")
st.selectbox("what you want to select", ['add','subtract'])
st.checkbox("what you want to select", ['add', 'subtract'])
st.radio("what you want to select", ['add', 'subtract'])
st.multiselect("what you want to select", ['add', 'subtract'])
st.slider("what you want to select", 0, 100)
st.file_uploader("upload your file")
st.color_picker("pick a color")
st.checkbox_11("what you want to select", ['add','mul', 'subtract'])
